# Generated by Django 5.0.6 on 2024-08-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_product_names_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='names_app',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/projects/'),
        ),
    ]
