# Generated by Django 5.0.6 on 2024-09-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_names_app_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='names_app',
            name='image',
        ),
    ]
